#!/bin/bash
cd $HOME
read -p "Enter 1 for 1.12.2 (Fastest)
Enter 2 for 1.16.5 (Latest)
" -n 1 -r
if [ $REPLY -eq 1 ]; then
    if [ ! -f lwjgl2arm32.tar.gz ]; then
        wget https://github.com/mikehooper/Minecraft/raw/main/lwjgl2arm32.tar.gz
	sudo mkdir lwjgl2arm32
	tar -zxf lwjgl2arm32.tar.gz -C ~/lwjgl2arm32
    fi
    if [ ! -f OptiFine_1.12.2_HD_U_G5.jar ]; then
        wget -O OptiFine_1.12.2_HD_U_G5.jar https://optifine.net/downloadx?f=OptiFine_1.12.2_HD_U_G5.jar&x=30f4ff6f655a91c80d2d5d83d586f49c
    	java -jar OptiFine_1.12.2_HD_U_G5.jar
    fi
elif [ $REPLY -eq 2 ]; then
    if [ ! -f lwjgl3arm32.tar.gz ]; then
        wget https://github.com/mikehooper/Minecraft/raw/main/lwjgl3arm32.tar.gz
        sudo mkdir lwjgl3arm32
        tar -zxf lwjgl3arm32.tar.gz -C ~/lwjgl3arm32
    fi
    if [ ! -f /home/$USER/OptiFine_1.16.5_HD_U_G7.jar ]; then
        wget -O OptiFine_1.16.5_HD_U_G7.jar https://optifine.net/downloadx?f=OptiFine_1.16.5_HD_U_G7.jar&x=e1c6567d2d3a4cf30464d0327f1df750
    	java -jar OptiFine_1.16.5_HD_U_G7.jar
    fi
    #if [ ! -f /home/$USER/IJAMinecrafts-OneBlock-1-16-4.zip ]; then
    #	wget https://ijaminecraft.com/download/map/oneblock/IJAMinecrafts-OneBlock-1-16-4.zip
    #   unzip -d /home/$USER/.minecraft/saves IJAMinecrafts-OneBlock-1-16-4.zip
    #fi
else
    echo Invalid
fi
if [ ! -f optionsof.txt ]; then
    wget https://raw.githubusercontent.com/kirbycope/mcje-pi/main/optionsof.txt
    sudo cp optionsof.txt /home/$USER/.minecraft/optionsof.txt
fi
if [ ! -d /usr/share/minecraftjava/Natives ]; then
    sudo mkdir /usr/share/minecraftjava/Natives
    cd /usr/share/minecraftjava/Natives
    sudo wget https://www.dropbox.com/s/4oxcvz3ky7a3x6f/liblwjgl.so
    sudo wget https://www.dropbox.com/s/m0r8e01jg2og36z/libopenal.so
fi
cd $HOME
echo "
Done!"
